apiVersion: v1
kind: Service
metadata:
  name: {{ include "logistics-wizard.fullname" . }}-webui
  labels:
    app: {{ include "logistics-wizard.name" . }}-webui
    chart: {{ include "logistics-wizard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app: {{ include "logistics-wizard.name" . }}-webui
    release: {{ .Release.Name }}
